### ISSUE TITLE
Add sound effects.

### ISSUE THREAD

**Issue by joneskj55** [joneskj55/simple-simon#1]
## Task
Add sound effects for each color similar to the ones in this video https://www.youtube.com/watch?v=XrNt1XM8xik.

**Comment by anmolsahu2k** [comment]
How does this look - [Simon Game](https://anmolsahu2k.github.io/simongame/)

**Comment by joneskj55** [comment]
Hi @anmolsahu2k. I should have clarified what I was looking for in terms of the sound effects. I was thinking something that sounds more like the Simon game in this video: https://www.youtube.com/watch?v=XrNt1XM8xik

**Comment by anmolsahu2k** [comment]
I understand what you are implying but if you are trying to implement Simon game, you could try from my repository [Simon Game](https://github.com/anmolsahu2k/simongame) and for the sounds you can just replace the files in `sounds` folder, but names of the files should be the same.

**Comment by joneskj55** [comment]
Issue closed by PR #2
